server:
  port: 9527
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  connection-timeout: 60000ms

spring:
  application:
    name: springcloud-nike-zuul

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

zuul:
  routes:
    api-a:
      path: /member/**
      serviceId: springcloud-nike-member
    api-b:
      path: /manage/**
      serviceId: springcloud-nike-manage
    api-c:
      path: /item/**
      serviceId: springcloud-nike-item
    api-d:
      path: /shoppingcart/**
      serviceId: springcloud-nike-shoppingcart
    api-e:
      path: /order/**
      serviceId: springcloud-nike-order
    api-f:
      path: /passport/**
      serviceId: springcloud-nike-passport
    api-g:
      path: /search/**
      serviceId: springcloud-nike-search
    api-h:
      path: /payment/**
      serviceId: springcloud-nike-payment
  ignored-services:
    springcloud-nike-member
    springcloud-nike-manage
    springcloud-nike-item
    springcloud-nike-shoppingcart
    springcloud-nike-order
    springcloud-nike-passport
    springcloud-nike-search
    springcloud-nike-payment

  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
#========================================================================================#
  #记住：一生之敌！！！ zuul拦截Cookie问题：配置这两项：
  #sensitiveHeaders:
  #add-host-header: true
#========================================================================================#
  sensitiveHeaders:
  add-host-header: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: springcloud_nike_zuul
info:
  app.name: springcloud_nike_zuul
  company.name: www.yadongjituan.com
  build.artifactId: springcloud_nike_zuul
  build.version: 0.0.1-SNAPSHOT

