server:
  port: 9001

spring:
  application:
    name: springcloud-nike-member
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/nike_member?serverTimezone=UTC&useSSL=false
  mvc:
    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: springcloud_nike_member
info:
  app.name: springcloud_nike_member
  company.name: www.yadongjituan.com
  build.artifactId: springcloud_nike_member
  build.version: 0.0.1-SNAPSHOT

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
#ribbon的超时时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000