server:
  port: 9009

spring:
  activemq:
    broker-url: tcp://192.168.255.140:61616
  application:
    name: springcloud-nike-activemq

activemq:
  listener:
    enable: true

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
#ribbon的超时时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: springcloud_nike_activemq

info:
  app.name: springcloud_nike_activemq
  company.name: www.yadongjituan.com
  build.artifactId: springcloud_nike_activemq
  build.version: 0.0.1-SNAPSHOT
