server:
  port: 9003

spring:
  application:
    name: springcloud-nike-item
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  mvc:
    static-path-pattern: /static/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: springcloud_nike_item
info:
  app.name: springcloud_nike_item
  company.name: www.yadongjituan.com
  build.artifactId: springcloud_nike_item
  build.version: 0.0.1-SNAPSHOT

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
#ribbon的超时时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000