server:
  port: 9006
  connection-timeout: 60000ms

spring:
  application:
    name: springcloud-nike-passport
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
#ribbon的超时时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: springcloud_nike_passport
info:
  app.name: springcloud_nike_passport
  company.name: www.yadongjituan.com
  build.artifactId: springcloud_nike_passport
  build.version: 0.0.1-SNAPSHOT


