server:
  port: 9005

spring:
  activemq:
    broker-url: tcp://192.168.255.140:61616
  application:
    name: springcloud-nike-order
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/nike_cartandorder?serverTimezone=UTC&useSSL=false
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  mvc:
    static-path-pattern: /static/**

activemq:
  listener:
    enable: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: springcloud_nike_order
info:
  app.name: springcloud_nike_order
  company.name: www.yadongjituan.com
  build.artifactId: springcloud_nike_order
  build.version: 0.0.1-SNAPSHOT

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
#ribbon的超时时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000